# -*- coding: utf-8 -*-
"""Flower classification project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GMUViLhBIL8yfmHDwci1vc8TtDiX-Uuf
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris=pd.read_csv("/content/IRIS.csv")
iris

"""Data Analysis"""

iris.shape

iris['species'].value_counts()

iris.info()

iris.describe()

sns.pairplot(iris,hue='species')

"""Splitting Dataset"""

x=iris.iloc[:,:4]
y=iris.iloc[:,-1]

x

y

"""Data Normalization"""

x=preprocessing.StandardScaler().fit_transform(x)

x

"""Train Test Split"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape

x_test.shape

"""KNN Model"""

knn=KNeighborsClassifier(n_neighbors=3)

knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)

accuracy=accuracy_score(y_test.values,y_pred)
accuracy

"""The accuracy is 100%"""

input=[[5,2.9,1,0.2]]

prediction=knn.predict(input)
prediction